#!/usr/bin/env bash
# Install Code Graph Search from source.
#
# Clones (or pulls) the repo into a cache dir, runs ./build.sh to
# produce the fat JAR, and creates wrapper scripts on the user's PATH
# so `code-graph-search` and `code-graph-mcp` are callable without
# knowing the JAR's absolute path.
#
# Prereqs (checked up front): java 21+, maven, npm, git.
# tree-sitter is optional (only needed for Go/Rust/C/C++/TS parsing)
# — a runtime warning surfaces in the app if missing.
#
# Env:
#   CGS_INSTALL_DIR   — where the source lives (default: ~/Library/Caches/code_graph_search on macOS,
#                       $XDG_CACHE_HOME/code_graph_search elsewhere)
#   CGS_BIN_DIR       — where wrapper scripts land (default: ~/.local/bin)
#   CGS_REPO_URL      — repo URL to clone from (default: https://github.com/geekychris/code_graph_search.git)
set -euo pipefail

REPO_URL="${CGS_REPO_URL:-https://github.com/geekychris/code_graph_search.git}"

case "$(uname -s)" in
  Darwin) DEFAULT_CACHE="$HOME/Library/Caches" ;;
  *)      DEFAULT_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}" ;;
esac
INSTALL_DIR="${CGS_INSTALL_DIR:-$DEFAULT_CACHE/code_graph_search}"
BIN_DIR="${CGS_BIN_DIR:-$HOME/.local/bin}"

# ---- prereq checks (fast fail with a clear install hint) ----
missing=()
for req in git java mvn npm; do
  if ! command -v "$req" >/dev/null 2>&1; then
    missing+=("$req")
  fi
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "Missing prereqs: ${missing[*]}" >&2
  echo "" >&2
  echo "Install via Homebrew:" >&2
  echo "  brew install git openjdk@21 maven node" >&2
  echo "" >&2
  echo "Note: this project requires Java 21 with preview features." >&2
  exit 1
fi

# Sanity-check Java version — must be 21+.
JAVA_MAJOR="$(java -version 2>&1 | head -1 | awk -F'"' '{print $2}' | awk -F'.' '{print $1}')"
if [ -z "$JAVA_MAJOR" ] || [ "$JAVA_MAJOR" -lt 21 ] 2>/dev/null; then
  echo "Detected Java version <21 (got: $(java -version 2>&1 | head -1))" >&2
  echo "Code Graph Search requires Java 21 with preview features." >&2
  echo "Install via: brew install openjdk@21" >&2
  exit 1
fi

# ---- clone or pull ----
mkdir -p "$(dirname "$INSTALL_DIR")"
if [ -d "$INSTALL_DIR/.git" ]; then
  echo "Updating existing checkout at $INSTALL_DIR ..."
  git -C "$INSTALL_DIR" pull --ff-only
else
  echo "Cloning $REPO_URL to $INSTALL_DIR ..."
  git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
fi

# ---- build ----
echo "Building fat JAR (mvn package -DskipTests) — this can take a few minutes on a cold cache..."
cd "$INSTALL_DIR"
bash ./build.sh

JAR="$INSTALL_DIR/app/target/code-graph-search.jar"
if [ ! -f "$JAR" ]; then
  echo "Build finished but JAR missing at $JAR" >&2
  exit 1
fi

# ---- wrappers on PATH ----
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/code-graph-search" <<EOF
#!/usr/bin/env bash
# Auto-generated by code_graph_search/scripts/install.sh
exec java --enable-preview -jar "$JAR" "\$@"
EOF
chmod +x "$BIN_DIR/code-graph-search"

cat > "$BIN_DIR/code-graph-mcp" <<EOF
#!/usr/bin/env bash
# Auto-generated by code_graph_search/scripts/install.sh
# MCP stdio mode: identical to run-mcp.sh but doesn't require the repo
# checkout to stay on PATH.
exec java --enable-preview -jar "$JAR" --mcp-stdio "\$@"
EOF
chmod +x "$BIN_DIR/code-graph-mcp"

echo ""
echo "Installed:"
echo "  Source: $INSTALL_DIR"
echo "  JAR:    $JAR"
echo "  CLI:    $BIN_DIR/code-graph-search"
echo "  MCP:    $BIN_DIR/code-graph-mcp"
echo ""
echo "First-time setup — pick a project to index:"
echo "  cp $INSTALL_DIR/config-example.yaml ~/.code-graph.yaml"
echo "  \$EDITOR ~/.code-graph.yaml   # set repos[0].path"
echo "  code-graph-search --config ~/.code-graph.yaml"
echo "  # then open http://localhost:8080"
echo ""
echo "Or, if you use Chief:  chief codegraph open <project>"
